### ISSUE TITLE
All queries must be logged

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#108]
This means they must go through either spExecuteSQL, spExecuteSQL2 spExecuteSQL3, depending on whether they need to filtered+logged, logged or filtered respectively.

**Comment by raddick** [comment]
Again, was this fixed as part of issue #127? @mtaghiza , @thakar ?

**Comment by mtaghiza** [comment]
they are all logged now in the sciserverlog database. spExecuteSQL also keeps logging what it was logging before in the weblog database.

**Comment by mtaghiza** [comment]
Works on prod version sciserver-v1.8.1. Closing...
