### ISSUE TITLE
ClientIP should be passed to WS that executes the query

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#115]
ClientIP is one of the fields that we log in the SkyServer logs, but it is not currently being passed to the Casjobs WS that executes SkyServer queries.  This means that it cannot be passed to spExecuteSQL[2] to be included in the logs.  We don't want to lose this information!

**Comment by raddick** [comment]
I think this is fixed, but it needs to be tested by making sure that clientIP is really being logged. @thakar , I can test if you tell me where the logs for scitest02 are stored.

**Comment by mtaghiza** [comment]
Yes, it is fixed. The ClientIP is catched in the Skyserver website and passed to SkyserverWS in the header. It is the logged in the sciserverlog database, column 'clientIP' of messages table.

**Comment by mtaghiza** [comment]
Confirmed fix in prod version sciserver-v1.8.1. Closing...
