### ISSUE TITLE
User queries should not be double-logged

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#116]
Currently, if a user is logged in to their SciServer account, all their SkyServer SQL queries will be logged both in their CasJobs account as well as in the SkyServer weblog db.  This will also be true for form queries initiated by the user in SkyServer, which in fact should not be logged at all in CasJobs because they will unnecessarily clutter up the user's job history.  We need a way to a) flag a casjobs WS query as coming from SkyServer, and b) turn off casjobs batchadmin logging for skyserver form queries.

**Comment by raddick** [comment]
@thakar , was this fixed as part of issue #127 ? Can we close this issue?

**Comment by mtaghiza** [comment]
All activity in SkyserverWS is logged in the sciserverlog database. The old spExecuteSQl procedure keeps logging in the weblog databse, but now with the option of disabling the logging.(in web.config)

**Comment by mtaghiza** [comment]
Issue not applicable anymore. Logging now in weblog db (for stats) and sciserverlog db (for skyserver user history tool) as of prod version sciserver-v1.8.1. Closing...
