### ISSUE TITLE
CrossID tool should connect to casjobs instead to directly querying the SDSS database.

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServer#117]
This issue is related to the fact that CrossID tool does query the database directly (apparently without logging anything), instead of sending queries to casjobs.

**Comment by raddick** [comment]
Did this get fixed as part of issue #127 , or is this separate? Do we need to test this now as part of the sciserver_v1_5_1 release? @mtaghiza ?

**Comment by mtaghiza** [comment]
Fixed. CrossID is now a new api entry point in SkyserverWS, which is called by the skyserver website when somebody runs the crossid tool.

**Comment by mtaghiza** [comment]
Confirmed the fix as of prod version sciserver-v1.8.1. Closing...
