### ISSUE TITLE
Consider a "Save to MyDB" option in all SkyServer searches

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#121]
On all the searching tools - SQL Search, Imaging Query, Radial, etc. - we already have options for HTML/CSV/JSON/etc. In each of these tools, consider having a "Save to MyDB" option as well. That way, the user can save their results into their MyDB accessible through CasJobs.

We're not sure yet whether we really want to spend the time to create this feature. Let's discuss further.

**Comment by mtaghiza** [comment]
Created this feature for all Search tools.

**Comment by mtaghiza** [comment]
Works nicely as of prod version sciserver-v1.8.1. Closing...
