### ISSUE TITLE
Add plate center to Plate Browser

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#124]
This is a feature request that came out of the SDSS plate workshop at Yerkes Observatory on September 19, 2015. The SDSS has a very cool program to give old SDSS plates to schools. Students feel a sense of ownership over both that plate and the part of the sky it was used to observe.

The problem is that SDSS has observed so many plates that it is very hard to tell which one the school has gotten. Teachers can look up the plate in the Plate Browser (link below), but that just gives the spectrum - there is no easy link to the area of the sky covered by that plate, which would be straightforward to create via the Navigate tool.

I implemented this, put it up on my dev space on scidev02, and I'm about to check the changes into the raddick_alerts branch of SkyServer.

**Comment by raddick** [comment]
I have made this change in the sciserver_raddick branch. I will merge it into the sciserver_vm branch.

**Comment by thakar** [comment]
I don't know where this link is supposed to be.  I don't see it on the Get images->Plates page.  Leaving it as needstest.

**Comment by mtaghiza** [comment]
This new feature appears in prod version sciserver-v1.8.1. Closing...
