### ISSUE TITLE
Several pages connect still directly to database

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServer#127]
I'll be changing the old connections to the new DatabaseSearch tool of SkyserverWS.
Please, check these pages and see whether they load, work correctly and the links in the pages work as well:

*** http://scitest02.pha.jhu.edu/SkyServer/en/help/docs/Intro.aspx

*** http://scitest02.pha.jhu.edu/SkyServer/en/help/Browser/Browser.aspx

*** http://scitest02.pha.jhu.edu/SkyServer/en/help/docs/TableDesc.aspx

*** right panel showing object details in 
      http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/navi.aspx
(the actual page is http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/shownearest.aspx, but we can't test anything there)

*** http://scitest02.pha.jhu.edu/SkyServer/en/help/docs/QS_userguide.aspx

*** http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/sqltoform.aspx
     (sends user query result-set list to http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/F_SQL.aspx)

*** Saving objects in the notebook (lower right) in
 http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/navi.aspx
(is internally using the page http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/Book.aspx)

*** http://scitest02.pha.jhu.edu/SkyServer/en/tools/getimg/Fields.aspx

*** http://scitest02.pha.jhu.edu/SkyServer/en/tools/getimg/Plate.aspx

*** http://scitest02.pha.jhu.edu/SkyServer/en/tools/getimg/Spectra.aspx

*** http://scitest02.pha.jhu.edu/SkyServer/en/tools/scroll/camcol.aspx

*** http://scitest02.pha.jhu.edu/SkyServer/en/tools/scroll/scrollhome.aspx

**Comment by mtaghiza** [comment]
ready to test now.

**Comment by raddick** [comment]
Verified that all these pages properly load. Spot-checked links on the pages - all the links I checked worked, so I'm confident that the links work.

Still need to test whether the queries were properly recorded in [SqlStatementLogUTC]. We should see hits to these pages coming from IP = '162.129.251.90' starting at about '2015-10-20 13:10:00'.

@thakar , in what server..database can we find the SQL logs associated with scitest02?

**Comment by mtaghiza** [comment]
Please, test everything again, since we had to revert most of those pages back to a direct database connection, or using a dedicated web service for them.

**Comment by mtaghiza** [comment]
Now all the tools talk to SkyserverWS. Only smaller pieces of data (not related to user queries) are obtained from a direct database query.

**Comment by mtaghiza** [comment]
Confirmed that my last comment is the one that applies to the current state of prod sciserver-v1.8.1. Closing...
