### ISSUE TITLE
Autoselect drawing options when clicking out from Image List to Navigate

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#138]
When in the Image List tool, you can click on any of the thumbnail images to bring up that particular object in the navigate tool. The navigate tool then launches in a new window, centered on the object - thus offering a larger, interactive view of the tiny thumbnail shown in Image List.

If any drawing options are selected in Image List, it would be helpful if those same options were auto-selected in the new Navigate window.

**Comment by mtaghiza** [comment]
Fixed. 
One disadvantage is that the new link will load slower, since will also have to add the drawing options for all other objects in the field. 
Please test again in version sciserver-v1.6.0 and see if if loading delay is acceptable.
