### ISSUE TITLE
Image List: removing a column causes an unhandled exception

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#139]
Removing a column from the image list's list window - or requesting the wrong number of columns with a SQL search - leads to the C# unhandled exception "yellow screen of death" shown below.

It looks like the problem manifests when the code tries to parse the ra and dec values.

<img width="934" alt="untitled-5" src="https://cloud.githubusercontent.com/assets/1709156/10429805/308fbda2-70c9-11e5-82a6-e1ac3ede83e7.png">

**Comment by mtaghiza** [comment]
Fixed. Will throw an error message in next version sciserver-v1.6.0

**Comment by mtaghiza** [comment]
Confirmed the fix as of sciserver-v1.8.1. Closing...
