### ISSUE TITLE
Quick Look and Explore: need to give user confirmation that object has been added to notebook

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#140]
When clicking "Add to Notes," the object is properly added to the notebook, but nothing appears to happen. The user needs confirmation that their action has had an effect.

Should be just a matter of adding a checkmark like in the other visual tools.

**Comment by mtaghiza** [comment]
Fixed. Also added this for the Explore tool. 
Will show in release sciserver-v1.6.0

**Comment by raddick** [comment]
Changed title to reflect inclusion in Explore tool as well
