### ISSUE TITLE
Radial/Rectangular Search: Click on objID fails

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#143]
In either the radial or rectangular search tools, click Submit Request to run the default query. You'll get a table of results. Click on one of the objID links in that table. A new window opens supposedly containing the Explore tool for that object, but it returns a Server Error.

**Comment by mtaghiza** [comment]
This is a known issue that comes as a result of what's referred in issue #41.

**Comment by raddick** [comment]
Cool, thanks. Should we find a different way of doing things so as to fix this issue, or is the fix just to fix issue #41 ?
