### ISSUE TITLE
All search tools: Upload to SAS does not upload objects

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#144]
On all the search tools, once you get the search results, there is a Submit button at the bottom of the page to upload a list of fields/spectra to the SAS. Clicking the button opens the appropriate SAS form, but DOES NOT pre-load query results into that form, which is what we promise in the button label.

**Comment by mtaghiza** [comment]
Tested this and the SAS links works with no problem: it loads the fields/spectra.
Please retest and close, otherwise could you specify what is not working with a screenshot.
