### ISSUE TITLE
Search Form: add links to explore tool in results table

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#146]
The test script for the search form tool specifies that clicking on the object ID for any row in the results table should lead to the Explore tool view for that object. This is the behavior for all other search tools, so the user expects this for the Search Form tool as well. But the table of results is displayed without links.

**Comment by mtaghiza** [comment]
Links cannot be provided since the query can be anything written by the user, so the backend is the same service used for SQLSearch, and this service provides no links.
