### ISSUE TITLE
Search Form: Search for Quasars fails

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#147]
On the Search Form, if you select "Quasars" from the "Show me" dropdown menu and then click Update,  it updates the query to read:

```
select top 10 p.objid, p.ra, p.dec
from photoobj p, specobj s
where p.objid=s.bestobjid and (s.class = 3 or s.class = 4)
```

But then submitting this query returns the following error:

```
SQL returned the following error: 
Failed to execute a query: Conversion failed when converting the varchar value 'GALAXY' 
to data type int.
```

The reason for this is that we changed the schema so that specObj.class is a character string saying 'STAR', 'GALAXY', etc. rather than an integer. The constructed query will need to be updated to use the new schema.

**Comment by mtaghiza** [comment]
Fixed. Now asks for objects where s.class = 'QSO'.
