### ISSUE TITLE
SQL Search tool: Does it make more sense to have "check syntax" as a separate button?

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#153]
On the SQL Search tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/sql.aspx

Right now, "check syntax" is a checkbox that you check before hitting Submit. If the box is checked, then clicking submit opens a syntax checker in a new window, where the query results would normally appear.

But thinking about user workflow: I would expect that they would want to check syntax BEFORE they think about submitting the query at all. So wouldn't it make more sense to make it a separate button?

Labeling as question, but we'll probably want to talk about this offline as well.

**Comment by mtaghiza** [comment]
Check syntax button works nicely in prod sciserver-v1.8.1. Closing...
