### ISSUE TITLE
SQL Search form: overflowing integer in "top" clause (But maybe I'm overthinking it? Discuss.)

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#154]
This might be over-userproofing (I just made up that word), but...

As part of the maximum object test for the SQL Search tool, I changed the "top" to an arbitrarily large number, resulting in this query:

```
-- This query does a table JOIN between the imaging (PhotoObj) and spectra
-- (SpecObj) tables and includes the necessary columns in the SELECT to upload
-- the results to the SAS (Science Archive Server) for FITS file retrieval.
SELECT TOP 34345534453453
   p.objid,p.ra,p.dec,p.u,p.g,p.r,p.i,p.z,
   p.run, p.rerun, p.camcol, p.field,
   s.specobjid, s.class, s.z as redshift,
   s.plate, s.mjd, s.fiberid
FROM PhotoObj AS p
   JOIN SpecObj AS s ON s.bestobjid = p.objid
WHERE 
   p.u BETWEEN 0 AND 19.6
   AND g BETWEEN 0 AND 20
```

which then returned this error:

```
SQL returned the following error: 
Failed to execute a query: The conversion of the varchar value '34345534453453' overflowed an int column.

Some tips: 
No multiple SQL commands allowed
```

I expect that what's happening is that the back-end code is parsing the query to check whether the number of results requested is greater than 500,000 so it can add a 500,000 to the query if needed. And in this query, a bigger-than-possible integer value is throwing this error.

I ask about whether this is "over-userproofing" because I don't expect this to come up much in the wild. BUT on the other hand, I'm pretty typical of an advanced public user (highly skilled teacher or citizen scientist), and I made this error happen in the course of basic testing.

Labeling as both "bug" and "question" - let's discuss by GitHub issue comment here.

**Comment by mtaghiza** [comment]
In c#, we have to try cast this as an integer before we can even compare it to 500,000, so we cannot scape this error message.

**Comment by mtaghiza** [comment]
Sorry, this is a message coming from spexecutesql, not from c# code.
If you think the error message is too cryptic for the common user, please talk to Sue so she can fix it.

**Comment by mtaghiza** [comment]
Don't think this is a problem anymore. People would know what is happening.

**Comment by mtaghiza** [comment]
Error message is the same as of sciserver-v1.8.1, and it's clear enough. Closing...
