### ISSUE TITLE
SQL Search: trying to return max objects results in a server error

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#156]
As part of the SkyServer testing, I removed the "top 10" from the default query in the SQL Search tool, expecting the query to hit the results limit and return 500,000 objects. Instead it returned a 502 server error (screenshot below). I get this error on any browser I try on either Mac or PC, so I know it's not a weird configuration thing.

<img width="1018" alt="untitled-6" src="https://cloud.githubusercontent.com/assets/1709156/10582231/d6b37f58-7654-11e5-86a3-f7740e59ec06.png">

**Comment by thakar** [comment]
Confirmed same behavior on v1_6_1, this is basically a timeout error I think but is not being caught.

**Comment by mtaghiza** [comment]
works in test.preprod, but takes a while.

**Comment by mtaghiza** [comment]
Confirmed that the query runs with no timeout in production version sciserver-v1.8.1, but it is up to the browser to display the table in html format with no problem :). Other formats download with no problem as well. Closing...
