### ISSUE TITLE
Cross-ID: Default cut-and-paste objects work only for Imaging match

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#158]
In the cross-ID tool, if you change the Search type from Imaging to either Spectra or Infrared Spectra:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/crossid/crossid.aspx

...then the objects shown by default under "Cut and paste your upload list here" result in "No objects have been found." This is technically correct but very confusing for the user.

Consider changing the default objects when the user changes the search type.

Again labeling as a Question to discuss-before-fixing. If there is a sound workflow or pedagogical reason for the behavior as it currently happens, I'm open to keeping it as-is. But I can't think of such a reason.

**Comment by mtaghiza** [comment]
Fixed. Just changed RA and DEC of object 'A4' to the coordinates of an object that is also in apogee.

**Comment by mtaghiza** [comment]
Works as of production version sciserver-v1.8.1. Closing...
