### ISSUE TITLE
Cross-ID: File uploads for all real-life files I've tried

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#162]
On the cross-ID tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/crossid/crossid.aspx

If I copy-and-paste the default values from the cut-and-paste textarea into a .txt or .csv file and then upload that file, the upload works fine and I get a result. I can then modify that .txt/.csv file and it still can upload.

But I've tried uploading several real-life files with positions to be cross-matched, and the tool consistently returns the following error message:

```
ERROR

Invalid column name 'up_ra'. Invalid column name 'up_dec'. Invalid column name 'up_ra'. Invalid column name 'up_dec'.
```

I get this error whether the file I upload is .csv or .txt , and whatever I use for the column separator (tab/comma/space).

Here's an example of a simple file that fails to upload:

[messier2.txt](https://github.com/idies/SkyServer/files/16217/messier2.txt)

**Comment by mtaghiza** [comment]
I cannot replicate this problem. I tried the same file (messier2.txt) and it uploads and runs with no problem (after adding line breaks, since the file has only one line). Please, retest again.
