### ISSUE TITLE
Cross-ID: Wrongly allows search radii bigger than 3 arcmin

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#163]
The search radius option on the cross-ID tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/crossid/crossid.aspx

says that the maximum search radius that can be entered is 3 arcmin. But this limit is not enforced. I can submit a query with a larger search radius, and it returns results. With a large enough search radius (e.g. 600), the query times out.

**Comment by mtaghiza** [comment]
Fixed.
