### ISSUE TITLE
Imaging Query Form: Can't search for both z magnitude and redshift

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#164]
In the Imaging Query Form, try selecting "model_mags" for imaging and "typical" for spectroscopy:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/IQS.aspx

Clicking Submit Request results in the following error message:

```
SQL returned the following error: 
Failed to execute a query: A column named 'z' already belongs to this DataTable.
```

This is because the photometric magnitude in the z wavelength and the redshift are both referred to as "z". The query is formatted correctly, but I suspect the data table object can't have two columns with the same name.

**Comment by raddick** [comment]
Interestingly, such a query DOES work correctly in the Spectroscopic Query Form:

<img width="1036" alt="untitled-9" src="https://cloud.githubusercontent.com/assets/1709156/10587170/f08b89f2-766d-11e5-831b-0aa6624344d1.png">

**Comment by mtaghiza** [comment]
Fixed.
