### ISSUE TITLE
All "Query Forms": Searching for flags/targets via selectors returns syntax error

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#165]
Running test number s_imaging_query_form_13 gives an incorrect syntax error as shown below. This syntax error occurs for any flag or combination of flags I search for (either in the ON or OFF menu).

Input:

<img width="651" alt="untitled-7" src="https://cloud.githubusercontent.com/assets/1709156/10586915/abf7ee44-766c-11e5-971a-3c19ac6df303.png">

Output:

<img width="918" alt="untitled-8" src="https://cloud.githubusercontent.com/assets/1709156/10586919/b1a49b80-766c-11e5-9966-5bd195adaeaa.png">

**Comment by raddick** [comment]
I originally filed this as happening in the Imaging Query Form when you select flags from the selector boxes, either the one marked ON or OFF. But it also occurs in the same context in the Spectro Query Form, and it also occurs when selecting Targets in the Spectro Query Form.

**Comment by mtaghiza** [comment]
Fixed.
