### ISSUE TITLE
Repeated menu selection in Tools sidebar menu: Scrolling Sky & SkyQuery CrossMatch

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#166]
See screenshot - gray highlight is repeated in the left-side sidebar menu. Should be an easy fix.

<img width="1012" alt="untitled-10" src="https://cloud.githubusercontent.com/assets/1709156/10588478/65ff0758-7674-11e5-941b-5814e753a452.png">

**Comment by mtaghiza** [comment]
fixed.

**Comment by mtaghiza** [comment]
Confirmed the fix as of prod sciserver-v1.8.1. Closing...
