### ISSUE TITLE
Explore: logging in from Explore page throws an error due to callback link

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#167]
As an anonymous SkyServer user, go to the Explore tool. While on the Explore tool, click the Login button on the SciServer control in the top right. That takes you to the login portal. Log in at the login portal. You'll be redirected back to the Explore tool, but the object you were looking at will have disappeared and been replaced with a "does not exist in the database" message, screenshot below.

See the URL, which is partially revealed in the screenshot. It looks like the callback URL is trying to pass the token as a parameter into the Explore tool in a way that the Explore tool doesn't recognize.

<img width="1018" alt="untitled-12" src="https://cloud.githubusercontent.com/assets/1709156/10588827/272a5eea-7676-11e5-99f2-e70040b19668.png">

**Comment by mtaghiza** [comment]
fixed

**Comment by mtaghiza** [comment]
fixed.

**Comment by mtaghiza** [comment]
Confirmed the fix as of prod sciserver-v1.8.1. Closing...
