### ISSUE TITLE
Radial/Rectangular Search: When using galactic coordiantes, report error messages in l/b

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#169]
In the radial and rectangular search tools, there are options to search using galactic coordiantes (l,b) in addition to the usual (ra,dec). The form does correctly check for out-of-range input in (l,b), but the error messages still refer to (ra,dec). Screenshots of input and output below.

Input in l/b:

![untitled-1](https://cloud.githubusercontent.com/assets/1709156/10609622/8c85e740-7712-11e5-8501-8e5a75204c00.jpg)

Output still shows error in ra/dec:

<img width="290" alt="untitled-2" src="https://cloud.githubusercontent.com/assets/1709156/10609630/91754868-7712-11e5-89ed-e8c2ccf3a4c7.png">

Should be an easy fix.

**Comment by mtaghiza** [comment]
fixed
