### ISSUE TITLE
Rectangular Search: conversion to (ra,dec) fails for some valid values of (l,b) ranges

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#170]
If you select "Infrared bands" and "Galactic (l and b)" in the rectangular search tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/search/rect.aspx

...the default input works, but for other valid values of (l,b) ranges, the search fails. For example, we know from the radial tool that there are APOGEE objects near (l,b) = (60,1), but entering a rectangle around there leads to the Rectangular Search failing. Screenshots below.

This seems to be an extremely subtle error - our conversion functions are correctly going from (l,b) to (ra,dec) for some values of (l,b), but are failing for some other values. It looks from the screenshots like the problem is that the min and max values are getting reversed.

We may need to talk to a galactic astronomer to make sure we get this right. I recommend Gail Zasowski, in office Bloomberg 519.

Input:

<img width="618" alt="untitled-3" src="https://cloud.githubusercontent.com/assets/1709156/10610200/cc05f87c-7714-11e5-87c7-7074a244f264.png">

Output:

<img width="563" alt="untitled-4" src="https://cloud.githubusercontent.com/assets/1709156/10610205/d1c82578-7714-11e5-92c8-ceea7f735048.png">

**Comment by thakar** [comment]
Yes, it is the reversal of RA values that is causing the problem.  The
conversion is correct, I confirmed with the NED online converter.  So if
you switch the order of the RA values in the query as below, it works
fine.  We will need to add logic to switch the values when necessary for
both RA and dec.

      Ani

SELECT TOP 10 p.apstar_id,
 p.apogee_id,p.ra, p.dec, p.glon, p.glat,
 p.vhelio_avg,p.vscatter,
 a.teff,a.logg,
 a.param_m_h
 FROM apogeeStar p
 JOIN aspcapStar a on a.apstar_id = p.apstar_id
 JOIN apogeeObject as o ON a.apogee_id=o.apogee_id
 WHERE p.ra BETWEEN 294.065617484804 AND 295.434546382682
 AND p.dec BETWEEN 23.0225810821478 AND 24.8758600091315

Your query output (max 500,000 rows):
apstar_idapogee_idradecglonglatvhelio_avgvscatterteffloggparam_m_hapogee.apo25m.c.stars.4241.2M19383216+24051242M19383216+2405124294.63401624.08680559.56404202211.16318883129-23.47640.225798-9999-9999-9999apogee.apo25m.c.stars.4241.2M19383199+24324312M19383199+2432431294.63329224.54532459.96340734771.3886370442234.54880.366139-9999-9999-9999apogee.apo25m.c.stars.4241.2M19395493+24172202M19395493+2417220294.97891624.2894559.89522009320.988803685364.621810.303148-9999-9999-9999apogee.apo25m.c.stars.4241.2M19395249+23185912M19395249+2318591294.96874523.3164259.04378418030.51757021708226.45360.247623-9999-9999-9999apogee.apo25m.c.stars.4241.2M19391023+23170192M19391023+2317019294.79266123.28387858.93585943620.64233779056429.37580.0606901-9999-9999-9999apogee.apo25m.c.stars.4241.2M19391416+24211792M19391416+2421179294.80901124.3549859.8760879581.15583368644-5.91710.0131437-9999-9999-9999apogee.apo25m.c.stars.4241.2M19391980+24204772M19391980+2420477294.83250524.34658859.87930206441.1330690652214.51580.289157-9999-9999-9999apogee.apo25m.c.stars.4241.2M19392056+24152362M19392056+2415236294.83570324.25657859.80234130241.0862762828834.71350.425072-9999-9999-9999apogee.apo25m.c.stars.4241.2M19381272+23420162M19381272+2342016294.55302323.70045959.19094512611.0383003847917.43190.00541368-9999-9999-9999apogee.apo25m.c.stars.4241.2M19381276+23344922M19381276+2334492294.55319923.58035959.08632254610.979295665677-33.02120.0129637-9999-9999-9999


--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Seek the wisdom of the ages, but look at the world through the eyes
of a child.  [Ron Wild]

**Comment by mtaghiza** [comment]
Fixed.
