### ISSUE TITLE
Motd.inc not working on SkyServer sites

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#175]
This is a bug on the production sites but we might as well fix it in sciserver. The mechanism to include a message of the day via the motd.inc file at the "en" level of the site is not working in the DR10 and DR12 SkyServer sites.  This seems to have been broken when we went to aspx, because it is working in DR1-DR9 sites (compare http://sdssorgtest.pha.jhu.edu/dr9/ with http://sdssorgtest.pha.jhu.edu/dr10 or dr12). This does not allow us to display a site-wide message for outages, for example.

**Comment by mtaghiza** [comment]
Fixed. added for now an empty file called motd.inc, and a reference to it in Home.aspx.

**Comment by mtaghiza** [comment]
Confirmed the fix in version sciserver-v1.8.1. Closing...
