### ISSUE TITLE
If you switch between equatorial and galactic coordinate systems in radial/rect search, you lose any changes you made

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#177]
If you modify the default values of the coordinates in either equatorial or galactic coordinate options in the radial/rectangular search forms, and then switch to the other coordinate system, you lose your changes and it shows the default values for that coord system. There is no way to get your original values back.  Shouldn't it be doing the conversion to the other coordinate system rather than overwriting the user's values with the default ones?

**Comment by mtaghiza** [comment]
Fixed. now does the conversion between galactic and equatorial coordinates.
