### ISSUE TITLE
Getting a cryptic error in Proximity search in IQS and SQS

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#178]
Selecting Proximity search with the default options throws the following error page in IQS and SQS:

An error occured

Exception while uploading data to create temp table.An item with the same key has already been added.

**Comment by mtaghiza** [comment]
This error has already been fixed in the new version. Please retest for the new release tomorrow.

**Comment by mtaghiza** [comment]
It is working with no error as of production version sciserver-v1.8.1. Closing...
