### ISSUE TITLE
Link to publications page on www.sdss.org is incorrect on SDSS Home menu and SDSS Pubs pages

### ISSUE THREAD

**Issue by bonbons0220** [sciserver/SkyServer#180]
The link to SDSS pubs page is incorrect on the Left Hand side menu on all SDSS pages on SkyServer, and on the Pubs page on SkyServer:
http://skyserver.sdss.org/dr12/en/sdss/pubs/pubshome.aspx
and 
http://skyserver.sdss.org/dr12/en/sdss/sdsshome.aspx

It is currently 
http://www.sdss.org/publications.php 
but should be 
http://www.sdss.org/science/publications/

Also check for other links like www.sdss.org/[pagename].php , they are probably incorrect, too, and might be www.sdss.org/pagename/.

**Comment by mtaghiza** [comment]
fixed.

**Comment by mtaghiza** [comment]
Links are now pointing to the correct URLs, as of production Skyserver version sciserver-v1.8.1. Closing...
