### ISSUE TITLE
SkyServer History Page Shows Error When Re-running Query that Had Outputted to MyDB

### ISSUE THREAD

**Issue by mikear69** [sciserver/SkyServer#184]
When I run a SQL Search query in SkyServer and output to MyDB it all works nicely.  But when in the History view, clicking on the link to re-run the query causes an error because the table already exists.  This is a valid error report and is clear enough, but for future updates we might want to think of a better way of exposing this – either not have a link, or change the message a bit, or default to a different output type say csv?

**Comment by mtaghiza** [comment]
Fixed. A solution would be to directly send the user to MyDB after clicking that link. But in that case the user won't be able to know what is the Skyserver URL that created the table (with all parameters already set in the URL) nor modify the parameters (unless the user creates the URL by copying and pasting the parameters by hand).
So as a solution just added to the page a link to MyDB.
