### ISSUE TITLE
"What's New on this Site" hasn't been updated since 2013

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#187]
That looks silly. I can add a news item about SciServer Altair if nothing else. I'll self-assign and do it after the release (rather than worrying about it now since it's not a showstopper).

**Comment by bonbons0220** [comment]
Or get rid of it and link to sciserver.org for all updates?

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by bonbons0220** [comment]
Closing this and recreating as "remove What's New from SkyServer". (Hoping you agree with this!)
