### ISSUE TITLE
Weird unhandled exception when pasting or clicking a URL

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#189]
I copied a URL (for a specific object in the Explore tool) from one browser to another and got the unhandled exception whose screenshot is below. Here is the link:

http://preprod.skyserver.sdss.org/dr12/en/tools/explore/DisplayResults.aspx?name=galSpecLineQuery&id=1237668296598749280&spec=2947691243863304192&apid=apogee.apo25m.s.stars.4128.2M13102744+1826172&fieldId=0x112d14c220880000

I got this error in all browsers I've tried.

![untitled-1](https://cloud.githubusercontent.com/assets/1709156/15079859/f81e3a9e-1388-11e6-9b84-806a7789cfe9.png)

**Comment by bonbons0220** [comment]
Where did you get the URL from? Can you list those steps? I'm not very familiar with the Explore tool.

**Comment by mtaghiza** [comment]
fixed.

**Comment by mtaghiza** [comment]
Confirmed that is fixed in production skyserver version sciserver-v1.8.1. Closing...
