### ISSUE TITLE
Explore TOC frame different shade of blue in different browsers

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#191]
A very minor thing, but now I'm curious... the table of contents frame in the Explore tool is a slightly different shade of blue in different browsers. See the image below (constructed from screenshots).

![untitled-4](https://cloud.githubusercontent.com/assets/1709156/15080375/b7aab8ae-138b-11e6-9872-d1707afca853.png)

**Comment by bonbons0220** [comment]
The blue is the same color in each instance. I took your img into photoshop and sampled the blue and it is #b0c4de in all cases. The reason they look different is an optical illusion. Your eye is averaging int he <hr>'s which are different colors in each browser. I doubt there are any styles set for the <hr>'s, so the browser default is used, which is different in each case.

**Comment by bonbons0220** [comment]
Above I was trying to write &lt;hr&gt;, but it got interpreted. Oopsie.
