### ISSUE TITLE
"Upload list of fields to the SAS" goes only to the SAS home page

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#192]
After you run a Radial or Rectangular query, you are given the option of "Upload a list of fields to the SAS." The Submit button there does indeed go to the SAS... but it leads to the SAS home page rather than a SAS page containing the objects you just queried.

![untitled-1](https://cloud.githubusercontent.com/assets/1709156/15080408/ece512a8-138b-11e6-893e-897605e6c0d2.png)

**Comment by mtaghiza** [comment]
Cannot replicate the issue. maybe it was a problem with the SAS webpage by itself.

**Comment by mtaghiza** [comment]
Works perfectly in production sciserver-v1.8.1. Closing...
