### ISSUE TITLE
Default SQL query return as FITS fails

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#193]
See error message in image below.

![untitled-3](https://cloud.githubusercontent.com/assets/1709156/15080813/d72f3446-138d-11e6-8bda-a113810a64b2.png)

**Comment by mtaghiza** [comment]
it works now.

**Comment by mtaghiza** [comment]
Confirmed that it works in production skyserver version sciserver-v1.8.1. Closing...
