### ISSUE TITLE
Can't save query results to MyDB because it tried to create a new user

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#195]
I'm logged in as "raddickpreprod" and using the SQL search tool on SkyServer.

I tried the default query, saving to MyDB with a new table name. I got a new window containing an error message (image below):

Authentication failed: Cannot create account; this email already exists.

(even though I'm logged in, so what does it mean by create account?)

This is an important new feature, so I'm afraid it might be a showstopper - unless I'm doing something wrong, in which case it's a documentation problem? Thanks!

![untitled-8](https://cloud.githubusercontent.com/assets/1709156/15081153/76896c4a-138f-11e6-833f-22674df969c9.png)

**Comment by bonbons0220** [comment]
Could not reproduce with a brand new testing account. Might be a Keystone
DB sync problem, as Dmitry and Ani described.

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu
