### ISSUE TITLE
Broken/missing links on API page

### ISSUE THREAD

**Issue by bonbons0220** [sciserver/SkyServer#201]
On http://skyserver.sdss.org/dr12/en/help/docs/api.aspx 7 example links are broken.

> http://skyserver.sdss.org/SkyserverWS/dr12/ImgCutout/getjpegR=1140&C=1&F=120&Z=12
> 
> http://skyserver.sdss.org/SkyserverWS/dr12/ImagingQuery/Proximity
> 
> http://skyserver.sdss.org/SkyserverWS/dr12/SIAP/getSIAPInfo?POS=132,12&SIZE=0.01
> 
> http://skyserver.sdss.org/SkyserverWS/dr12/ImagingQuery/Rectangular?limit=52&decmin=64&decmax=64.1&imgparams=typical,minimal&magType=model&format=csv
> 
> http://skyserver.sdss.org/SkyserverWS/dr12/SpectroQuery/ProximitySpectro
> 
> http://skyserver.sdss.org/dr12/en/help/docs/%3C!--%=globals.SIAPSearch%--%32&decmin=64&decmax=64.1&imgparams=typical,minimal&magType=model&format=csv
> 
> http://skyserver.sdss.org/dr12/en/tools/crossid/x_crossid.aspx?searchType=pup_id+and+x.objID%3Dp.objID+%0D%0AORDER+BY+x.up_id%0D%0A%09%09&format=html

There are also two sections missing that are linked from the Table 2 TOC:

> Get Frame: http://skyserver.sdss.org/dr12/en/help/docs/api.aspx#getframe
> Get Scrolling Sky Image: http://skyserver.sdss.org/dr12/en/help/docs/api.aspx#getssky

**Comment by mtaghiza** [comment]
fixed
