### ISSUE TITLE
Database indices page is broken (en/help/docs/indices.aspx missing)

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#205]
The link that shows the database indices defined on each table is broken, and apparently has been broken since DR10!  If you go to the Help page "About the Database", then click on "Database Indices", it takes you to a section of the page where there is a link to display the database indices "Click here to view a table of all the current indices defined on the data.". If you click on that link, you get an error message: 

Server Error in '/dr12' Application.

The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /dr12/en/help/docs/indices.aspx

**Comment by mtaghiza** [comment]
Fixed. Added missing indices.aspx page.

**Comment by thakar** [comment]
Thanks. Did you have to create it from scratch or was there a version of it
somewhere?

```
  Ani
```

## 

Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar

## http://www.sdss.jhu.edu/%7Ethakar

I don't mind that you think slowly, but I do mind that you are
publishing faster than you think. [Wolfgang Pauli, Nobel physicist]

**Comment by mtaghiza** [comment]
from scratch, just by looking at the last working page (in DR9).

**Comment by thakar** [comment]
Yeah, that's what I figured, this was one of the things that slipped
through the cracks during the refactoring.  Not a good sign that nobody
complained about it since DR10!

```
   Ani
```

## 

Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar

## http://www.sdss.jhu.edu/%7Ethakar

I don't mind that you think slowly, but I do mind that you are
publishing faster than you think. [Wolfgang Pauli, Nobel physicist]

**Comment by thakar** [comment]
Hi Manu,

A desired enhancement of this feature would be to not have each table name
be listed multiple times for each index, i.e. for PhotoObjAll it should
show the name only once in the leftmost column, preferably vertically
centered, for all the PhotoObjAll indices.  This is a feature request over
and above what was there before, so not high priority :-) .

```
    Ani
```

## 

Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar

## http://www.sdss.jhu.edu/%7Ethakar

I don't mind that you think slowly, but I do mind that you are
publishing faster than you think. [Wolfgang Pauli, Nobel physicist]

**Comment by mtaghiza** [comment]
Indices page present now in version 1.8.1.  Closing...
