### ISSUE TITLE
Explore: Clicking "Look up common name" overwrites "observed in MaNGA"

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#206]
Posting before-and-after screenshots below.

Before clicking the button:
![before](https://cloud.githubusercontent.com/assets/1709156/17254186/b2e53938-5581-11e6-932d-707bfc95c634.png)

After clicking the button:
![after](https://cloud.githubusercontent.com/assets/1709156/17254194/b9979bfe-5581-11e6-9dde-aa9e0c86201e.png)

**Comment by mtaghiza** [comment]
fixed. Will be showing in the next DR13 version (after 1.8.1).
