### ISSUE TITLE
DR12 and DR13 imaging query gives same result for Extended Sources and Point Sources

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#211]
Issue title: DR12 and DR13 imaging query gives same result for Extended Sources and Point Sources

From: Chris Fassnacht

Category: Bug

Severity: Mild

Description:
Steps 5 and 7 return the same number of targets and, having checked the first few in the returned lists, they appear to be the same objects in each list. In other words, the generated SQL query did not appear to use the object type (extended or point) in selecting sources. I am trying to just get galaxies out of this exercise, so this is a problem. In early data releases, I used the exact same procedure and got different results (as expected) when selecting point or extended, so this appears to be a somewhat new bug. Any help that you could give would be very much appreciated. Thanks!

Steps to reproduce:
1. Go to imaging query web site (URL pasted above)
2. Choose cone search with 10.0 arcmin search radius (center is 41.64213 -8.42672)
3. Choose to retrieve radec and model_mags from imaging and typical from spectroscopy
4. Select only Extended Sources
5. Submit
6. Unselect Extended sources and select Point Sources
7. Submit

**Comment by raddick** [comment]
Message from Ani on 8/16/16 - I think this has been fixed now?

Thanks ... well, I guess we have our reason to release a new version now, since this fixes broken functionality.  We need to do a round of testing first though.  Let's go through all the elements of the form queries to make sure everything works.

```
  Ani
```

@mtaghiza, could you confirm whether this has been fixed in SkyServer and pushed to the public site, and if so, please close this issue? Thanks!

**Comment by mtaghiza** [comment]
yes, the fix was included in the last SkyServer release.
