### ISSUE TITLE
Arcminute limit error on Search Form

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#213]
Issue title: arcminute limit error

From: Preston

Category: Question

Severity: Moderate

Description:
The help button says that the arcminute limits are from 0-600, but when I put an input greater than 60 the feedback says the limit is 0-60. 

http://skyserver.sdss.org/dr12/en/tools/search/form/searchform.aspx

**Comment by mtaghiza** [comment]
given the info given by the user, there is no way to find where the error took place. Could you please add the stack trace (if there is any attached to the error report), or contact the user for more specific info? thanks @raddick 
this even looks like a documentation error, more than a bug.

**Comment by mtaghiza** [comment]
Found the problem. The user is probably using the footprint check, for which the limit in the radius has  been 60' in all previous data releases. This limit is missing in the help page. Will add it.

**Comment by mtaghiza** [comment]
limit is already set in help page.
