### ISSUE TITLE
CrossID fails with long input tables (maybe fixed already?)

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#214]
## This is an old bug report, so maybe it's fixed already. Just want to make sure it gets tracked.

Issue title:
CrossID fails with long input tables

Category: Question

Severity: Moderate

Description:
After the implementation of SciServer, it seems that CrossID cannot handle long tables anymore.
Before SciServer, I had never had any problems with it. Inputting files with over 1000 rows gave no problem at all. Now it seems that this limit has gone down to some hundreds. This is very inconvenient to people working with large catalogs. My input table has less than 80KB, and the output is way less than 500000 objects, so the query is well within the limits described on the CrossID page. Is there perhaps a new limit, or is this a bug?
Thanks in advance.

Steps to reproduce:
1. Input long table (~300 rows) containing plate, mjd, and fiber in cross ID to obtain ra and dec for the objects. Sintax:
SELECT s.ra, s.dec, s.plate, s.mjd, s.fiberid
FROM #upload u
JOIN SpecObjAll s ON (s.plate=u.up_plate AND s.mjd=u.up_mjd AND s.fiberID=u.up_fiber)
2. An error will be returned:
String or binary data would be truncated. The statement has been terminated. Arithmetic overflow occurred. Arithmetic overflow occurred.
(extra) 3. Splitting same table in two parts (each with ~150 rows) and using each as one input gives no error, indicating the problem does not seem to be on the input itself, but on its size.

**Comment by mtaghiza** [comment]
The limit is imposed by SQL Server, since it is a maximum of 1000 rows per insert statement. I created a command that runs multiple batches of inserts (1000 rows each), which solves the problem. Tested this for an upload of 10000 rows and it works. Please, test this in the next release, and close if passes testing.
