### ISSUE TITLE
Microsoft Edge does not siplay aspx files properly

### ISSUE THREAD

**Issue by glemson** [sciserver/SkyServer#218]
When running a query (tried radial and SQL) in skyserver on Windows 10's Edge the resulting page is not displayed as an HTML page, instead a question "What do you want to do with x_result.aspx" is posed. 
Comment from Mitya on Slack: " It's probably because the response is missing the "Content-Type: text/html" header. Most likely a SkyServer problem."

**Comment by mtaghiza** [comment]
Fixed. Content-Type was present in all formats, but in html format, only appeared half of it for some reason.
