### ISSUE TITLE
SQS can't search by HMS/DMS

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#220]
Bug report from a user on the Spectrum Query Search tool of SkyServer (http://skyserver.sdss.org/dr13/en/tools/search/SQS.aspx) below. The problem is that searching by decimal degrees works, but the HMS/DMS to decimal degree conversion doesn't work, so users can't search by that method.

This is SDSS helpdesk question 10322, thread pasted below, with the original user submission followed by the user's answer to a follow-up question from Ben Weaver.

-----------------------------------------------
Hi.
The decimal degree coordinate search for DR13 APOGEE works, but the HH:MM:SS.ss  or HH MM SS.ss format does not work. Typing into the search box by hand - not a file upload (though that could be broken too).

Hi Benjamin,

I tried a number of coordinates - any should reflect the error.
But here is a specific example. [also, sorry I didn’t see the Report Error button previously]

Proximity box:  All nearby checked, 1.0 arcmin search (no file upload used)

19:44:00.00,+24:20:00.00,1.0

Resulting error
Technical info:
{"ErrorCode":500,"ErrorType":"InternalServerError","ErrorMessage":"Incorrect syntax near ':'.","LogMessageID":"3ffdd9c8-c729-4e1d-b15f-f0135ae7b58c","LogTime":"2016-12-19T13:20:40.0262554-05:00”} 

It does not matter if this is in colon format as above, or spaces. 
Only the decimal degrees format seems to work.

Cheers, Guy
-----------------

**Comment by mtaghiza** [comment]
fixed
