### ISSUE TITLE
Add BOSS/eBOSS target flags to SQS

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#221]
In the course of investigating issue #220, Ben Weaver found another problem with the SQS. We need to add BOSS and eBOSS target flags to the form, so that users can search for BOSS and eBOSS objects as well.

Hello y'all,

I confirmed this problem, but there is another issue here.  This person
specifically mentions APOGEE spectra, but I don't see how to select
those on this form.  For example, no APOGEE targeting flags appear in
the target flag boxes.  In fact, I don't even see BOSS or eBOSS flags in
there!  In other words, even in DR13, this page only seems to know about
SDSS-I/II spectra.

Kia ora koutou,
Benjamin Alan Weaver

**Comment by mtaghiza** [comment]
Added BOSS and eBOSS flags filtering in Spectroscopic Search tool. Adding Apogee flags is not necessary, since they are already included in the Infrared Spectroscopic Search tool.
