### ISSUE TITLE
Update SciServer version to v1.9.3

### ISSUE THREAD

**Issue by bonbons0220** [sciserver/SkyServer#223]
Update SciServer version to v1.9.3 in the Message of the Day (MOTD) in branch sciserver_vm.
No user-facing changes to document.

When done, DO NOT CLOSE ISSUE, instead

1. Mark as FIXED,
2. Add comment with commit hash
3. Assign to me (bonbons0220)

**Comment by mtaghiza** [comment]
For the record, the message of the day (./motd-SkyServer.inc) is no longer part of the project, so that we don't need to do any commits whenever we change it.

**Comment by raddick** [comment]
Manu will have to do this since I don't have write permission to the directory where motd-SkyServer.inc is:

http://test.preprod.skyserver.sdss.org

For next time, I've asked Lance for permission. But for this time, reassigning to Manu.

**Comment by mtaghiza** [comment]
It's done. As explain above, there's no commit ID for that.
BTW Jordan, not sure if Lance is back yet, to make sure maybe you can ask Jan or somebody else.

**Comment by mtaghiza** [comment]
Bonnie, could you please test both DR12 and DR13 sites? Thanks!

**Comment by bonbons0220** [comment]
Please fix link in MOTD. It goes to http://www.sciserver.org/support/updates/#overview1p9p1, which is the link to the "SciServer Altair v1.9.1" section, not 1.9.3. It should go to 
http://www.sciserver.org/support/updates/#overview1p9p3 .

**Comment by mtaghiza** [comment]
link fixed.

**Comment by bonbons0220** [comment]
Also, typo in MOTD: both exclamation mark and period!.
You could just remove this whole line because it looks like you have a choice about which version of SciServer to use. If you remove this line, make the heading a link to the website. 
(Hint: put the link outside the heading <a href="..."><h2>... )

> NEW: SciServer Altair v1.9.3  (new window) is now available!.

**Comment by mtaghiza** [comment]
Ready, removed the extra period :)
