### ISSUE TITLE
Broken links in SciServer Quasars project

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#233]
This is from a SciServer bug report. It has to do with this page:

http://skyserver.sdss.org/dr14/en/proj/advanced/quasars/whatare.aspx

The links in the "fiber" list in Exercise 2 return the following error:

The file '/dr14/en/get/specByPF.aspx' does not exist.

I think I know how to fix this. Self-assigning.

ORIGINAL HELPDESK REPORT:

From: Maria Babakhanyan Stone

Category: Bug

Severity: Mild

Description:
Broken links

Steps to reproduce:
1.On this page, http://skyserver.sdss.org/dr14/en/proj/advanced/quasars/whatare.aspx
if you click the Fiber numbers as instructed by the exercise,
you get broken links with the following error message
"""""
An error has occurred in Skyserver
The file '/dr14/en/get/specByPF.aspx' does not exist.
Click to Report Error
or inform sciserver-helpdesk@jhu.edu
""""

**Comment by bonbons0220** [comment]
Can you coordinate with Mike Allison to make sure the update is propagated
into the material he is migrating to Voyages?

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

Johns Hopkins University

3400 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by raddick** [comment]
Fixed by replacing links with what I found by hand from using the Get Spectrum tool
