### ISSUE TITLE
Make SciServer logo in top-right box a link to sciserver.org

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#235]
Thus users can always go back to sciserver and link to other tools like compute

**Comment by bonbons0220** [comment]
This will be part of the Messaging (javascript injection) update.

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

Johns Hopkins University

3400 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by raddick** [comment]
Awesomesauce! I'll close this issue since it's recorded as part of the use case for that Messaging update.
