### ISSUE TITLE
Redshifting of spectra does not work on redshift finder educational tool

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServer#24]
The tool is in here:

http://scitest02.pha.jhu.edu/SkyServer/en/proj/advanced/hubble/redfinder/xcor.htm

Clicking buttons does not work anymore.

**Comment by raddick** [comment]
Manu, you were fixing this, right? IIRC, it was now working in some browsers, but still not in other browsers. Which ones?

**Comment by raddick** [comment]
We just got another SDSS helpdesk question asking about this, so I think it's increasingly important to get this fixed in the next release.

**Comment by deoyani** [comment]
Fixed this error.

**Comment by mtaghiza** [comment]
Just tested in version sciserver-v1.8.1. Issue is fixed. Closing issue...
