### ISSUE TITLE
Not all queries sent to Casjobs store a keyword specifying which component was the query generated from.

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/SkyServer#42]
Adding this as a reminder. Check that all queries created in skyserver do in fact specify the place where they were created (e.g.: 'QuickLook: Summary'). Check this for SkyServerWS as well.

**Comment by raddick** [comment]
Any update on whether this has been fixed? This is behind-the-scenes enough that I'm not sure how to test it.

**Comment by mtaghiza** [comment]
Fixed.

**Comment by raddick** [comment]
Has Manu's fix been tested on sciserver_v1_4_0 by someone other than Manu? If so, and if it's working, we can close this issue.

**Comment by mtaghiza** [comment]
We are still refactoring and deciding which queries go where. So it's better if I check this at the very end.

**Comment by raddick** [comment]
This is fixed, right? Again, I can test if @thakar can tell me where to find the logs for scitest02.

**Comment by mtaghiza** [comment]
Now the sciserverlog database stores that keyword in column 'taskname' of the 'messages' table. 
You can confirm this by using a skyserver tool and looking at the new entry in the table.

**Comment by mtaghiza** [comment]
Just tested in prod version sciserver-v1.8.1. Issue is fixed. Closing issue...
