### ISSUE TITLE
Logos in Quick Look and search boxes are outdated

### ISSUE THREAD

**Issue by thakar** [sciserver/SkyServer#70]
The Quick Look page and the small search boxes that come up when you click on Search by objID, ra,dec etc. all have the old SDSS-!/II logo, it hasn't even been updated to SDSS-III logo.  We should leapfrog to the new integrated SDSS logo.

**Comment by mtaghiza** [comment]
Fixed. Please look in all places where you thing there might be a logo and see if its the updated one. I tried to update most pages (e.g. navigate, explore, quicklook, chart), but not sure if some other pages are missing.

**Comment by raddick** [comment]
Found in just one other place: In the print view in the visual tools. Screenshot:

<img width="660" alt="untitled-11" src="https://cloud.githubusercontent.com/assets/1709156/10588635/279d676a-7675-11e5-8afa-a81d204de26d.png">

**Comment by raddick** [comment]
Since one more fix is needed, I'm changing the milestone to sciserver_v1_6_0.

**Comment by mtaghiza** [comment]
Fixed

**Comment by thakar** [comment]
Still needs to be fixed in Finding Chart and Navigate "print" views.

**Comment by mtaghiza** [comment]
Fixed.

**Comment by mtaghiza** [comment]
Tested in prod version sciserver-v1.8.1. Issue fixed. Closing issue...
