### ISSUE TITLE
Finding chart: notify user when query in "Use query to mark objects" fails

### ISSUE THREAD

**Issue by raddick** [sciserver/SkyServer#98]
In the Finding Chart tool:

http://scitest02.pha.jhu.edu/SkyServer/en/tools/chart/image.aspx

If you write an invalid query in the "Use query to mark objects" textbox, the query doesn't run (as indeed it should not), but the user doesn't get any notification, so the user doesn't know why the image didn't change. We need a notification.

This was uncovered in the course of performing test s_chart_14 , which called for writing SQL injection code in that box and verifying that it would not execute.

**Comment by mtaghiza** [comment]
This is not easy to do. That query is run inside image cutout WS, which calculates whether the retrieved objects fall inside the image field of view (and plots them if they do). And the only thing Image cutout is designed to return is an image, and not a text message saying whether the query was successful in retrieving objects or if it was even syntactically correct.

**Comment by thakar** [comment]
This is a long-standing problem.  Even when imgcutout times out or has
another problem, we get messages of the type "getFrames() has failed ..."
displayed within a blank image window, which is not user-friendly or
graceful really.  I don't know if there's a way around this but it's
certainly come up before.

    Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
If the stars should appear one night in a thousand years, how would
men believe and adore? [Ralph Waldo Emerson]
